version: "3.7"

networks:
  network:
  test:

volumes:
  pgdata:
  tmp:
  opdata:
  bundle:
  pgdata-test:
  tmp-test:

x-op-restart-policy: &restart_policy
  restart: unless-stopped
x-op-build: &build
  context: .
  dockerfile: ./docker/dev/backend/Dockerfile
  args:
    DEV_UID: $DEV_UID
    DEV_GID: $DEV_GID
x-op-image: &image
  image:
    openproject/dev:latest

services:
  db:
    image: postgres:9
    <<: *restart_policy
    stop_grace_period: "3s"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - network

  cache:
    image: memcached
    <<: *restart_policy
    networks:
      - network

  backend:
    build:
      <<: *build
      target: develop
    <<: *image
    <<: *restart_policy
    command: run-app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      RAILS_CACHE_STORE: memcache
      OPENPROJECT_CACHE__MEMCACHE__SERVER: cache:11211
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    volumes:
      - ".:/home/dev/openproject"
      - "opdata:/var/openproject/assets"
      - "bundle:/usr/local/bundle"
      - "tmp:/home/dev/openproject/tmp"
    depends_on:
      - db
      - cache
    networks:
      - network

  frontend:
    build:
      context: .
      dockerfile: ./docker/dev/frontend/Dockerfile
      args:
        DEV_UID: $DEV_UID
        DEV_GID: $DEV_GID
    command: "npm run serve"
    volumes:
      - ".:/home/dev/openproject"
    ports:
      - "4200:4200"
    environment:
      PROXY_HOSTNAME: backend
    networks:
      - network
    depends_on:
      - backend

######### Testing stuff below ############

  db-test:
    image: postgres:9
    stop_grace_period: "3s"
    volumes:
      - "pgdata-test:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: openproject
      POSTGRES_USER: openproject
      POSTGRES_PASSWORD: openproject
    networks:
      - test

  backend-test:
    build:
      context: .
      dockerfile: ./docker/dev/backend/Dockerfile
      args:
        DEV_UID: $DEV_UID
        DEV_GID: $DEV_GID
      target: test
    command: run-app
    networks:
      - test
    depends_on:
      - db-test
      - selenium-hub
    environment:
      RAILS_ENV: test
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
      DATABASE_URL: postgresql://openproject:openproject@db-test/openproject
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
      SELENIUM_GRID_URL: http://selenium-hub:4444/wd/hub
      CAPYBARA_APP_HOST: http://backend-test:3000
    volumes:
      - ".:/home/dev/openproject"
      - "opdata:/var/openproject/assets"
      - "bundle:/usr/local/bundle"
      - "tmp-test:/home/dev/openproject/tmp"

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    depends_on:
      - chrome
      - firefox
      - opera
    networks:
      - test
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test
    ports:
      - 5900:5900
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test
    ports:
      - 5901:5900
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  opera:
    image: selenium/node-opera-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test
    ports:
      - 5902:5900
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
